name: Pull Request Linting

on:
  pull_request:
    branches: ["master"]
    paths: ["src/**", "public/**"]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ESLint
        run: |
          npm install eslint@9.18.0
          npm install eslint-plugin-astro@1.3.1
          npm install typescript@5.7.3
          npm install typescript-eslint@8.21.0
          npm install @eslint/js@9.18.0
          npm install @typescript-eslint/parser@8.21.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint src
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
