name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: ["master"]
    paths: ["src/**", "public/**"]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ESLint
        run: |
          npm install eslint@9.18.0
          npm install eslint-plugin-astro@1.3.1
          npm install typescript@5.7.3
          npm install typescript-eslint@8.21.0
          npm install @eslint/js@9.18.0
          npm install @typescript-eslint/parser@8.21.0
      - name: Run ESLint
        run: npx eslint src
  build-and-deploy:
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: ./dist
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ./dist
